<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <ApplicationManifest>app.manifest</ApplicationManifest>

    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>

    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
    <PublishDir>../../bin/core/host/startup/gog</PublishDir>
    <AssemblyName>deadcells</AssemblyName>

    <PublishTrimmed>true</PublishTrimmed>
    <ApplicationIcon>icon.ico</ApplicationIcon>
    <RootNamespace>GOGStartShell</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SteamLauncher\SteamLauncher.csproj" />
  </ItemGroup>
  <Import Project="../../IncludeSteamworkNET.props" />
</Project>
