<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="libsteam_api.so">
      <LogicalName>libsteam_api.so</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="steam_api64.dll">
      <LogicalName>steam_api64.dll</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>
  <Import Project="../../IncludeSteamworkNET.props" />
</Project>
