<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>Hashlink</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    
    <PackageReference Include="MonoMod.Core" Version="1.3.4" />
    
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    
    <ProjectReference Include="..\HashlinkNET.Bytecode\HashlinkNET.Bytecode.csproj" />
    <ProjectReference Include="..\ModCore.Common\ModCore.Common.csproj" />
    <ProjectReference Include="..\ModCore.Native\ModCore.Native.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Hashlink.HashlinkNative">
      <Static>True</Static>
    </Using>
  </ItemGroup>

</Project>
