<Project>
  <PropertyGroup>
    <Version>35.10.2</Version>
    <TargetFramework>net10.0</TargetFramework>
    <RepositoryUrl>https://github.com/dead-cells-core-modding/core</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Company>Dead Cells Core Modding</Company>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CopyDocumentationFilesFromPackages>true</CopyDocumentationFilesFromPackages>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Platforms>AnyCPU;x64</Platforms>
    <NoWarn>$(NoWarn);MSB3270</NoWarn>
  </PropertyGroup>

</Project>