<Project>
  <PropertyGroup>
    <Version>35.9.7</Version>
    <TargetFramework>net10.0</TargetFramework>
    <RepositoryUrl>https://github.com/dead-cells-core-modding/core</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Company>Dead Cells Core Modding</Company>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CopyDocumentationFilesFromPackages>true</CopyDocumentationFilesFromPackages>
  </PropertyGroup>

</Project>