<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ModType>library</ModType>
    <GenerateSinglePakFile>true</GenerateSinglePakFile>
    <NoModCore>true</NoModCore>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DeadCellsCoreModding.MDK" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <PackAssets Include="raw_assets\**\*" RootInPak="dccm-core" />
  </ItemGroup>

  <Target Name="CopyResPak" AfterTargets="MergeAllPaks">
    <Copy SourceFiles="$(MergedPakPath)"
          DestinationFiles="../../bin/core/host/res.pak" UseHardlinksIfPossible="true" />
  </Target>
  

</Project>
