<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
    <PublishDir>../../bin/core/host/startup</PublishDir>

   
    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>
    <Platforms>x64</Platforms>

    <ApplicationIcon>icon.ico</ApplicationIcon>

    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)' == 'Windows_NT' and '$(Configuration)' != 'Debug'">
    <UseNativeAOT>true</UseNativeAOT>

    <OptimizationPreference>Size</OptimizationPreference>
    <PublishAot>true</PublishAot>
  </PropertyGroup>

  <ItemGroup Condition="'$(UseNativeAOT)' == 'true'">
    <NativeLibrary Include="../../bin/core/native/win-x64/host_lib.lib" />

    <LinkerArg Include="/DEF:./exports.def" />
  </ItemGroup>
  
  <PropertyGroup Condition="'$(UseNativeAOT)' != 'true'">
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <PublishReadyToRun>true</PublishReadyToRun>
    <RollForward>LatestMajor</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="icon.ico" />
  </ItemGroup>
  
  <ItemGroup>
    <None Update="steam_appid.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
