<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HaxeProxy\HaxeProxy.csproj" />
    <ProjectReference Include="..\ModCore.Common\ModCore.Common.csproj" />
    <ProjectReference Include="..\ModCore.Native\ModCore.Native.csproj" />
  </ItemGroup>

</Project>
