<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <ApplicationIcon>icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>

    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>

    <IncludeNativeLibrariesForSelfExtract>false</IncludeNativeLibrariesForSelfExtract>

    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
    <PublishDir>../../bin/core/host/startup/steam</PublishDir>
    <AssemblyName>deadcells</AssemblyName>

    <PublishTrimmed>true</PublishTrimmed>
    <DebugType>embedded</DebugType>
    <RootNamespace>SteamStartShell</RootNamespace>
   
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>



  <ItemGroup>
    <ProjectReference Include="..\SteamLauncher\SteamLauncher.csproj" />
  </ItemGroup>
</Project>
