<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <ApplicationIcon>icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>

    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>

    <IncludeNativeLibrariesForSelfExtract>false</IncludeNativeLibrariesForSelfExtract>

    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
    <PublishDir>../../bin/core/host/startup/steam</PublishDir>
    <AssemblyName>deadcells</AssemblyName>

    <PublishTrimmed>true</PublishTrimmed>

    <RootNamespace>SteamStartShell</RootNamespace>
   
  </PropertyGroup>

  <ItemGroup>
    <None Remove="steam_api64.dll" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="steam_api64.dll">
      <LogicalName>steam_api64.dll</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <Import Project="../../IncludeSteamworkNET.props" />

</Project>
