<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="K4os.Hash.xxHash" Version="1.0.8" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\tools\BytecodeMapping\BytecodeMapping.csproj" />
    <ProjectReference Include="..\HashlinkNET.Bytecode\HashlinkNET.Bytecode.csproj" />
    <ProjectReference Include="..\HaxeDocs\HaxeDocs.csproj" />
    <ProjectReference Include="..\HaxeProxy\HaxeProxy.csproj" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
