<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RollForward>LatestMajor</RollForward>

    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>

    <PublishDir>../bin/tools</PublishDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\sources\HashlinkNET.Compiler\HashlinkNET.Compiler.csproj" />
    <ProjectReference Include="..\..\sources\HaxeDocs\HaxeDocs.csproj" />
    <ProjectReference Include="..\..\tools\BytecodeMapping\BytecodeMapping.csproj" />
    <ProjectReference Include="..\..\sources\NonPublicNativeMembers\NonPublicNativeMembers.csproj" />
    <ProjectReference Include="..\GameRes.Core\GameRes.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="steam_api64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Import Project="../../IncludeSteamworkNET.props"/>
</Project>
