<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RollForward>LatestMajor</RollForward>

    <ServerGarbageCollection>true</ServerGarbageCollection>
    <ConcurrentGarbageCollection>false</ConcurrentGarbageCollection>

    <PublishDir>../bin/tools</PublishDir>
  </PropertyGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'linux-arm64'">
    <DefineConstants>$(DefineConstants);ARM64</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.57.2" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\sources\HashlinkNET.Compiler\HashlinkNET.Compiler.csproj" />
    <ProjectReference Include="..\..\sources\HaxeDocs\HaxeDocs.csproj" />
    <ProjectReference Include="..\..\tools\BytecodeMapping\BytecodeMapping.csproj" />
    <ProjectReference Include="..\..\sources\NonPublicNativeMembers\NonPublicNativeMembers.csproj" />
    <ProjectReference Include="..\GameRes.Core\GameRes.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="steam_api64.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="tmxtool.hl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup Condition="'$(RuntimeIdentifier)' == 'linux-arm64'">
    <DefineConstants>$(DefineConstants);ARM64</DefineConstants>
  </PropertyGroup>

  <Import Project="../../IncludeSteamworkNET.props" Condition="'$(RuntimeIdentifier)' == '' or !$(RuntimeIdentifier.Contains('arm64'))" />

  <ItemGroup Condition="'$(RuntimeIdentifier)' == 'linux-arm64'">
    <Compile Remove="CallResultUtils.cs" />
    <Compile Remove="Commands\Steam\*.cs" />
  </ItemGroup>
</Project>
